// <auto-generated />
using Expenses.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using System;

namespace Expenses.Migrations
{
    [DbContext(typeof(ExpensesContext))]
    partial class ExpensesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Expenses.Models.ExpenseViewModels.Expense", b =>
                {
                    b.Property<int>("ExpenseId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<DateTime?>("DateFor");

                    b.Property<string>("Description");

                    b.Property<bool>("IAmPayer");

                    b.Property<int?>("InteractorId");

                    b.Property<string>("Name");

                    b.Property<bool>("Paid");

                    b.Property<DateTime?>("PaidDate");

                    b.Property<double?>("PaidValue");

                    b.Property<double>("Value");

                    b.HasKey("ExpenseId");

                    b.HasIndex("InteractorId");

                    b.ToTable("Expense");
                });

            modelBuilder.Entity("Expenses.Models.ExpenseViewModels.ExpenseImage", b =>
                {
                    b.Property<int>("ExpenseImageId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ExpenseId");

                    b.Property<byte[]>("Image");

                    b.HasKey("ExpenseImageId");

                    b.HasIndex("ExpenseId");

                    b.ToTable("ExpenseImage");
                });

            modelBuilder.Entity("Expenses.Models.ExpenseViewModels.Interactor", b =>
                {
                    b.Property<int>("InteractorId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("InteractorId");

                    b.ToTable("Interactor");
                });

            modelBuilder.Entity("Expenses.Models.ExpenseViewModels.Expense", b =>
                {
                    b.HasOne("Expenses.Models.ExpenseViewModels.Interactor", "Interactor")
                        .WithMany("Expenses")
                        .HasForeignKey("InteractorId");
                });

            modelBuilder.Entity("Expenses.Models.ExpenseViewModels.ExpenseImage", b =>
                {
                    b.HasOne("Expenses.Models.ExpenseViewModels.Expense", "Expense")
                        .WithMany("ExpenseImages")
                        .HasForeignKey("ExpenseId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
